# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartCycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartCycle

  pod "AlamofireImage"
  target 'SmartCycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartCycleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
